### ISSUE TITLE
Orders list keeps auto-scrolling to the top

### ISSUE THREAD

**Issue by jansako** [KomodoPlatform/atomicDEX-Pro#125]
Win10.

Issue: The current orders list auto-jumps to the top every few seconds. Possibly the result of the orderbook call.

Expected: When scrolling the orderbook, the window position does not auto-jump :-)

Nice to have: remember the position of the list when toggling between tabs Trade/Orders/History

**Comment by naezith** [comment]
Thanks for reporting. Reason of this happening is, when list updates, entire QML list object is being recreated. We had similar issues at some other places and searched for solutions but there isn't a pure QML solution to this as I remember. Only way was to use a dependency which prevents the list recreation and changes only the items which really changed. 

We'll discuss this, adding a dependency just for this is not preferable.

**Comment by jansako** [comment]
Just reducing the frequency of update would be a huge improvement. Right now if you were to have a list of 20 orders, you can never see the last one as it would jump to the top before you can scroll all the way down :-)

Consider these options:
- only recreate the list when switching tabs OR once a minute, maybe 2 minutes
- add a 'refresh' button that would rebuild it on demand
- split the list into smaller (screen sized?- LOL) segments, or even each order on a separate segment. Then you can refresh them individually per above. You would not need to separate the segments visually, so the user would not know at all.

I can imagine you guys are probably working on some sort of grid/sort system for the order lists, so I am just throwing out ideas :-).

**Comment by lilszi** [comment]
still an issue

**Comment by tonymorony** [comment]
thats looks actual for all list (dashboard, orderbooks) on tick

**Comment by tonymorony** [comment]
fixed in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/367

**Comment by lilszi** [comment]
still happening in 0.2.0 in trade window when selecting coin from list

**Comment by tonymorony** [comment]
@lilszi hmm I was not able to reproduce that with coins seletction in both base and rel lists - could you please 
however, there is similar problem for orderbook's order selection list in 0.2.0 - but orderbook is under rework so it will be resolved

**Comment by tonymorony** [comment]
can't reproduce it anymore
